export const GET_UNCHECK_NOGLES = 'GET_UNCHECK_NOGLES';
export const SET_CHECKED_NOGLES = 'SET_CHECKED_NOGLES';
export const SET_UNCHECK_NOGLES = 'SET_UNCHECK_NOGLES';

export default {
  GET_UNCHECK_NOGLES,
  SET_CHECKED_NOGLES,
  SET_UNCHECK_NOGLES,
};
